
# choose between flatfile, mysql 
storage: mysql

statsCommand:
    show:
    - "Last seen"
    - "Playtime"
    - "Blocks broken"
    - "Joins"
    - "Kill"
    - "PVP"
    - "PVP streak"
    # - "Blocks broken,world=world|world_nether"
    # - "PVP,weapon=!Bow
    
config-version: 1

disabled:
- "Stat1"