
# choose between flatfile, mysql 
storage: mysql

statsCommand:
    show:
    - "playtime,world=world"
    - "playtime,world=!world"
    - "blocks broken,world=world|world_nether"
    
config-version: 1