name: Stats
main: nl.lolmewn.stats.Main
version: maven-version-number-jenkins-build-number
description: Advanced statistics tracker and viewer. Check out your gathered stats and show them off!
author: Lolmewn
commands:
  lolmewnstats:
    aliases: stats
    usage: /<command>
    description: Main commands for Stats 